@extends('admin.fournisseurs.ajout')
@extends('admin.fournisseurs.liste')
@extends('admin.personel.creer')
@extends('admin.produits.ajout')
@extends('admin.ventes.ventes')
@extends('admin.categories.ajouter')
@extends('admin.stock.liste')
