@extends('admin.fournisseur.ajout')
@extends('admin.fournisseur.liste')
@extends('admin.fournisseur.commande')
@extends('admin.fournisseur.livraison')
@extends('admin.personel.creer')
@extends('admin.produit.ajout')
@extends('admin.ventes.ventes')
@extends('admin.categories.ajouter')
